'use client'
import { useState, useEffect } from 'react'
import { Header } from '@/components/dashboard/Header'
import { ArciumBadge, ConfidentialSalaryBadge } from '@/components/dashboard/ArciumBadge'
import { Shield, Download, FileText, CheckCircle2, ExternalLink, Zap } from 'lucide-react'
import { formatCurrency, formatDate, generatePayslipId } from '@/lib/utils'
import { getExplorerUrl } from '@/lib/solana'
import { toast } from 'sonner'

interface Payment {
  id: string
  employee_name: string
  employee_role: string
  amount: number
  tx_signature: string
  paid_at: string
  pay_period_start: string
  pay_period_end: string
  arcium_proof: string
}

export default function PayslipsPage() {
  const [payments, setPayments] = useState<Payment[]>([])
  const [loading, setLoading] = useState(true)
  const [selectedPayslip, setSelectedPayslip] = useState<Payment | null>(null)

  useEffect(() => {
    fetch('/api/employee/payments')
      .then(r => r.json())
      .then(d => setPayments(d.payments || []))
      .catch(() => toast.error('Failed to load payslips'))
      .finally(() => setLoading(false))
  }, [])

  const downloadPayslip = (payment: Payment) => {
    const payslipId = generatePayslipId()
    const content = `
FLASHPAY PRIVATE — PAYSLIP
===========================
Payslip ID: ${payslipId}
Generated: ${new Date().toLocaleDateString()}

EMPLOYEE INFORMATION
--------------------
Name: ${payment.employee_name}
Role: ${payment.employee_role}

PAY PERIOD
----------
From: ${formatDate(payment.pay_period_start)}
To: ${formatDate(payment.pay_period_end)}
Paid: ${formatDate(payment.paid_at)}

COMPENSATION
------------
Gross Amount: ${formatCurrency(payment.amount)}
Currency: USDC (Solana)

TRANSACTION
-----------
Tx Signature: ${payment.tx_signature}
Network: Solana Devnet
Status: Confirmed

PRIVACY & VERIFICATION
-----------------------
Arcium Proof: ${payment.arcium_proof}
Privacy Layer: Arcium MPC (Confidential Compute)
Zero-Knowledge: Salary amount verified without public disclosure

This payslip is generated by FlashPay Private.
Salary data is protected by Arcium's multi-party computation network.
    `.trim()

    const blob = new Blob([content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `flashpay-payslip-${payslipId}.txt`
    a.click()
    toast.success('Payslip downloaded!')
  }

  return (
    <div className="fade-in">
      <Header title="Payslips" subtitle="Download your salary statements" />
      <div className="p-6 space-y-6">
        {/* Privacy badge */}
        <div className="flex items-center gap-3 rounded-xl border border-[#6c44fc]/20 bg-[#6c44fc]/6 p-4">
          <Shield className="h-5 w-5 text-[#6c44fc] shrink-0" />
          <div className="flex-1">
            <p className="text-sm font-semibold text-white">Confidential Payslips</p>
            <p className="text-xs text-[#666666] mt-0.5">
              Each payslip includes an Arcium zero-knowledge proof confirming payment. Salary amounts are visible only to you.
            </p>
          </div>
          <ArciumBadge size="sm" />
        </div>

        {loading ? (
          <div className="grid gap-4">
            {[1,2,3].map(i => <div key={i} className="h-24 rounded-xl shimmer" />)}
          </div>
        ) : payments.length === 0 ? (
          <div className="py-16 text-center">
            <FileText className="mx-auto h-10 w-10 text-[#444444] mb-3" />
            <p className="text-[#666666] text-sm">No payslips yet. They&apos;ll appear here after your first payment.</p>
          </div>
        ) : (
          <div className="grid gap-3">
            {payments.map(payment => (
              <div
                key={payment.id}
                className="rounded-xl border border-white/8 bg-[#141414] p-5 hover:border-white/15 transition-colors"
              >
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-3">
                    <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#6c44fc]/15 border border-[#6c44fc]/20">
                      <FileText className="h-5 w-5 text-[#6c44fc]" />
                    </div>
                    <div>
                      <p className="text-sm font-semibold text-white">
                        Payslip — {formatDate(payment.paid_at)}
                      </p>
                      <p className="text-xs text-[#666666]">
                        {formatDate(payment.pay_period_start)} – {formatDate(payment.pay_period_end)}
                      </p>
                    </div>
                  </div>
                  <div className="flex items-center gap-3">
                    <ConfidentialSalaryBadge />
                    <span className="text-sm font-bold text-[#95ffdd]">{formatCurrency(payment.amount)}</span>
                    <a
                      href={getExplorerUrl(payment.tx_signature)}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="rounded-lg p-1.5 text-[#666666] hover:bg-white/8 hover:text-[#6c44fc] transition-colors"
                    >
                      <ExternalLink className="h-4 w-4" />
                    </a>
                    <button
                      onClick={() => downloadPayslip(payment)}
                      className="flex items-center gap-1.5 rounded-lg border border-white/10 bg-white/5 px-3 py-1.5 text-xs font-medium text-white/70 hover:bg-white/10 transition-colors"
                    >
                      <Download className="h-3.5 w-3.5" />Download
                    </button>
                  </div>
                </div>

                {/* Arcium proof */}
                <div className="mt-3 flex items-center gap-2 text-xs text-[#444444] font-mono">
                  <Shield className="h-3 w-3 text-[#6c44fc]" />
                  Proof: {payment.arcium_proof.slice(0, 40)}…
                </div>
              </div>
            ))}
          </div>
        )}

        <div className="flex items-center justify-center gap-2 text-xs text-[#444444]">
          <Zap className="h-3 w-3 text-[#5de2da]" />
          Payments verified on Solana · Privacy by Arcium
        </div>
      </div>
    </div>
  )
}
